title: Your Blog Title
author: Some Username or name
email: email@domain.com
description: >
  Include site description here. Will be used for description meta tag in header and feed.xml site desc.

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: ibubeboo
    github: georgeipsum

theme: rebuild-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag