title: Your Blog Title
subtitle: some subtitle
author: Some username or name
email: email@domain.com
description: >
  Include site description here. Will be used for description meta tag in header and feed.xml site desc.

timezone: America/Los_Angeles
excerpt_separator: <!--more-->

show_excerpts: false

rebuild:
  date_format: "%b %-d, %Y"

  header_img: "/assets/img/header-bg.jpg"

  social_links:
    twitter: twitter
    github: github

theme: rebuild-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag